version: '3.7'

services:
  php:
    image: php:8-cli-alpine
    volumes:
      - ./:/app
    user: ${HOST_UID}:${HOST_GID}
    working_dir: /app
    init: true

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    user: ${HOST_UID}:${HOST_GID}
